repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=2000"]
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: "^.idea/.*$"
      - id: forbid-new-submodules
      - id: mixed-line-ending
      # - id: no-commit-to-branch
      # args: [--branch, main]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.2
    hooks:
      - id: prettier
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.73.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tflint
      # - id: terraform_tfsec # Disabling because it is taking forever with the lambda function, despite it not being used by Terraform?
      - id: terraform_validate
