# https://taskfile.dev

version: "3"

tasks:
  init:
    desc: Initializes the dev environment
    cmds:
      # - asdf plugin add ruby # This is temporary in till the ruby plugin is added to anvil.  See: https://github.com/saic-oss/anvil/pull/39
      - asdf install
      - pre-commit install

  validate:
    desc: Validate the pre-commit hooks
    cmds:
      - task init
      - pre-commit run -a

  plan:
    desc: Runs a Terraform Plan
    cmds:
      - terraform plan -var-file="env/main.tfvars"
    dir: terraform

  deploy:
    desc: Runs a Terraform Apply
    cmds:
      - terraform apply -var-file="env/main.tfvars"
    dir: terraform

  serve:
    desc: Runs the Jekyll
    cmds:
      - bundle install
      - bundle exec jekyll serve --watch --host 0.0.0.0
    dir: docs
