# https://taskfile.dev

version: "3"

tasks:
  init:
    desc: Initializes the dev environment
    cmds:
      - asdf install
      - pre-commit install

  validate:
    desc: Validate the pre-commit hooks
    cmds:
      - task init
      - pre-commit run -a

  plan:
    desc: Runs a Terraform Plan
    cmds:
      - terraform plan -var-file="env/main.tfvars"
    dir: terraform

  deploy:
    desc: Runs a Terraform Apply
    cmds:
      - terraform apply -var-file="env/main.tfvars"
    dir: terraform
